### ISSUE TITLE
Too many automatic redirections were attempted

### ISSUE THREAD

**Issue by Sano** [Roemer/Waddu#15]
at System.Net.HttpWebRequest.GetResponse()
   at Waddu.Core.CookieManager.GetWowAceCookies(String loginName, String loginPassword)
   at Waddu.Core.CookieManager.GetCookies(AddonSiteId addonSiteId)
   at Waddu.Core.WebHelper.GetHtml(String url, AddonSiteId addonSiteId)
   at Waddu.Core.AddonSites.SiteWowAce.ParseInfoSite(Mapping mapping)
   at Waddu.Core.AddonSites.SiteWowAce.GetSiteAddon(Mapping mapping)
   at Waddu.Core.AddonSites.SiteWowAce.GetVersion(Mapping mapping)
   at Waddu.Core.BusinessObjects.Mapping.CheckRemote()
   at Waddu.Core.WorkItems.WorkItemAddonVersionCheck.DoWork(WorkerThread workerThread)
   at Waddu.Core.WorkerThread.ThreadProc(Object param)

Failing on both WowAce and CurseForge.  Curse works fine.  Looks like they may have changed the Cookie content/address.

**Comment by Sano** [comment]
Ok, really strange.  Not doing this on my dev box.  Closing this until I do a little more research.
