### ISSUE TITLE
Value does not fall within the expected range

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Roemer/Waddu#5]
```
What steps will reproduce the problem?
Atempting to update an addon

What is the expected output? What do you see instead?

Value does not fall within the expected range.
   at System.Windows.Forms.UnsafeNativeMethods.IWebBrowser2.Navigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
   at System.Windows.Forms.WebBrowser.PerformNavigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
   at System.Windows.Forms.WebBrowser.PerformNavigateHelper(String urlString, Boolean newWindow, String targetFrameName, Byte[] postData, String headers)
   at System.Windows.Forms.WebBrowser.Navigate(String urlString)
   at Waddu.UI.Forms.WebBrowserForm..ctor(String url, AddonSiteId addonSiteId, String addonName)
   at Waddu.Core.AddonSites.SiteWowAce.GetFilePath(Mapping mapping)
   at Waddu.Core.BusinessObjects.Mapping.GetFilePath()
   at Waddu.Core.WorkItems.WorkItemAddonUpdate.DoWork(WorkerThread workerThread)
   at Waddu.Core.WorkerThread.ThreadProc(Object param)
What version of the product are you using? On what operating system?
Alpha 6 Maintenance Release 14, XP SP3, IE8

Please provide any additional information below.


```

Original issue reported on code.google.com by `esben.ka...@gmail.com` on 1 Dec 2011 at 1:40

**Comment by Roemer** [comment]
Cannot reproduce.
