### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Roemer/Waddu#6]
```
What steps will reproduce the problem?
1. Select wowinterface as Mapping.
2. Update

What is the expected output? What do you see instead?
Expected output is addon should update.

Error:
Object reference not set to an instance of an object.
   at Waddu.Core.AddonSites.SiteWowInterface.ParseXmlSite(Mapping mapping, SiteAddon addon)
   at Waddu.Core.AddonSites.SiteWowInterface.GetFilePath(Mapping mapping)
   at Waddu.Core.WorkItems.WorkItemAddonUpdate.DoWork(WorkerThread workerThread)
   at Waddu.Core.WorkerThread.ThreadProc(Object param)

What version of the product are you using? On what operating system?
v.0.6.15.0
Windows 7 x64 Home

Please provide any additional information below.
All other sites appear to work fine.
```

Original issue reported on code.google.com by `suisilve...@gmail.com` on 18 Mar 2013 at 10:18

**Comment by Roemer** [comment]
Works now
